---
- hosts: all
  become: true
  tasks:

  - name: Installing Apache2 and PHP Packages
    package:
      name:
        - "{{ apache_package  }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# added 'when' statement to specify Ubuntu as Linux distro
