---
- hosts: all
  become: true
  tasks:

  - name: Update Repository Index (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing Apache2 & PHP Packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

# added 'when' statement to specify Ubuntu as Linux distro

  - name: Update Repository Index (CentOS)
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Installing Apache2 & PHP Packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
